In [1]:
# Python3 program explaining work
# of randint() function

# imports random module
import random

# Generates a random number between
# a given positive range
r1 = random.randint(0, 10)
print("Random number between 0 and 10 is % s" % (r1))

# Generates a random number between
# two given negative range
r2 = random.randint(-10, -1)
print("Random number between -10 and -1 is % d" % (r2))

# Generates a random number between
# a positive and a negative range
r3 = random.randint(-5, 5)
print("Random number between -5 and 5 is % d" % (r3))

Random number between 0 and 10 is 3
Random number between -10 and -1 is -6
Random number between -5 and 5 is -5


In [8]:
# importing randint function
# from random module
from random import randint
# Function which generates a new
# random number everytime it executes
def generator():
	return randint(1, 10)
	
# Function takes user input and returns
# true or false depending whether the
# user wins the lucky draw!
def rand_guess():

	# calls generator() which returns a
	# random integer between 1 and 10
	random_number = generator()
	
	# defining the number of
	# guesses the user gets
	guess_left = 5

	# Setting a flag variable to check
	# the win-condition for user
	flag = 0

	# looping the number of times
	# the user gets chances
	while guess_left > 0:

		# Taking a input from the user
		guess = int(input("Pick your number to "
					"enter the lucky draw\n"))

		# checking whether user's guess
		# matches the generated win-condition
		if guess == random_number:

			# setting flag as 1 if user guessses
			# correctly and then loop is broken
			flag = 1
			break
		
		else:
			
			# If user's choice doesn't match
			# win-condition then it is printed
			print("Wrong Guess!!")

		# Decrementing number of
		# guesses left by 1
		guess_left -= 1

	# If win-condition is satisfied then,
	# the function rand_guess returns True
	if flag is 1:
		return True
	# Else the function returns False
	else:
		return False

# Driver code
if __name__ == '__main__':
	if rand_guess() is True:
		print("Congrats!! You Win.")
	else :
		print("Sorry, You Lost!")

<>:55: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:55: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\ACE COMPUTER STORE\AppData\Local\Temp/ipykernel_21048/2445773843.py:55: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if flag is 1:


Wrong Guess!!
Wrong Guess!!
Wrong Guess!!
Wrong Guess!!
Wrong Guess!!
Sorry, You Lost!


In [9]:
from random import randint
#create a list of play options
t = ["Rock", "Paper", "Scissors"]

#assign a random play to the computer
computer = t[randint(0,2)]

#set player to False
player = False

while player == False:
#set player to True
    player = input("Rock, Paper, Scissors? ")
    if player == computer:
        print("Tie!")
    elif player == "Rock":
        if computer == "Paper":
            print("You lose!", computer, "covers", player)
        else:
            print("You win!", player, "smashes", computer)
    elif player == "Paper":
        if computer == "Scissors":
            print("You lose!", computer, "cut", player)
        else:
            print("You win!", player, "covers", computer)
    elif player == "Scissors":
        if computer == "Rock":
            print("You lose...", computer, "smashes", player)
        else:
            print("You win!", player, "cut", computer)
    else:
        print("That's not a valid play. Check your spelling!")
    #player was set to True, but we want it to be False so the loop continues
    player = False
    computer = t[randint(0,2)]

You lose! Paper covers Rock
You win! Scissors cut Paper
Tie!
You lose! Scissors cut Paper
Tie!
You lose! Paper covers Rock
Tie!
Tie!
You win! Rock smashes Scissors
You lose... Rock smashes Scissors
You lose... Rock smashes Scissors
Tie!
You win! Scissors cut Paper
That's not a valid play. Check your spelling!


KeyboardInterrupt: Interrupted by user

In [15]:
import pandas as pd

biodata = {
    'Nama': 'Yusuf',
    'TTL': 'Saumlaki, 11 Oktober 2003',
    'Usia': 18,
    'Hobi': ['Olahraga dan Makan'],
    'Tinggi badan': 165.9,
    'Berat badan': 56.8,
    'Cita-cita': 'Polisi'
}

df1 = pd.DataFrame(biodata)
df1

Nama                        TTL  Usia                Hobi  Tinggi badan  \
0  Yusuf  Saumlaki, 11 Oktober 2003    18  Olahraga dan Makan         165.9   

   Berat badan Cita-cita  
0         56.8    Polisi

In [23]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [26]:
a = arr.transpose()
print(a)

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [27]:
b = arr * np.array([2, 10, 4, 8, 5])
print(b)

[[  2  20  12  32  25]
 [ 12  70  32  72  50]
 [ 22 120  52 112  75]
 [ 32 170  72 152 100]]


In [30]:
c = a * np.array([1, 0, 9, 7, 3])
d = c.transpose()
print(d)

ValueError: operands could not be broadcast together with shapes (5,4) (5,) 